### ISSUE TITLE
Homepage & Getting Started UI Fixes

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#187]
The following are minor fixes to be done:
Homepage:
- [x] “Create an NFT” card seems not have the same hover state as “Crypto Dappy Course” card.
- [x] The external link arrow doesn’t look in the same position as the other arrows - maybe pushed down and centered a bit more?
- [x] Hide the 'stars' and 'author' section for now in the tools

Getting Started:
- [x] Remove the external link upward pointing arrow on the “Cadence” card in “Core Concepts”
- [x] Hide “view all SDKs” button
- [x] Hover state over buttons (ie. main CTA button at the top) need some smoother animation

Both pages:
- [x] Hide email/newsletter component

**Comment by neilZon** [comment]
Just a few items I might need a bit of clarification on:

> * The external link arrow doesn’t look in the same position as the other arrows - maybe pushed down and centered a bit more?

The external icon and right-chevron icons are aligned in the same way (aligned with the title of the list item) do we want to change all the icons here to align vertically in the list item?
<img width="219" alt="Screen Shot 2022-06-16 at 3 39 14 PM" src="https://user-images.githubusercontent.com/46465568/174170348-326524b5-94ab-4552-bb0b-8aa7fc6835ca.png">


<br />

> *  Remove the external link upward pointing arrow on the “Cadence” card in “Core Concepts”

For the "core Concepts" section do we want to remove the external link icon totally, even for links that are external or because the cadence page we want to link to is going to be internal to the site?
<br /><br />

**Comment by srinjoyc** [comment]
1) It feels like the arrow should be moved down a little and to the left maybe to make it more uniform - even if it is centered, we might want to artificially offset it a little to see if it can be visually more appealing.
2) For now, yes because it'll eventually be an internal link.

**Comment by neilZon** [comment]
I removed the stars and author from the "Tools" section from the Home page but what about the "SDK" cards in the getting started page? They are basically the same component
