### ISSUE TITLE
[due June 20] Dynamic Components in MDX files

### ISSUE THREAD

**Issue by srinjoyc** [onflow/next-docs-v1#50]
How does dynamic components on the mdx pages (pulled from GH)

For example:

- [ ] Contributors
- [x]  FLIPs -> Pulled out to a separate issue: 
https://github.com/onflow/next-docs-v1/issues/117
- [ ] Comments
- [ ] Last edited, etc.

Full list and examples coming soon.

All this will need to be updated through a github action on the originating repo to update the cache with appropriate values (on merge of PR).

**Comment by codingone21** [comment]
Update:
Created a _draft_ PR that 
- uses [Github API,](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests) which pulls PRs from /flow repository for open FLIP PRs
- converts PR information into a list of FlipCellProps, which should be fed into the component
- routing to api/flips

Next:
- Add another github API for getting the number of comments, currently just getting the url for comments

**Comment by codingone21** [comment]
For the issue #138: 
There are some issues with polling (using useSWR) vs the way we decided to 'fetch' in the utils directory and treat them like APIs due to polling (There was an error running the data loader for route routes/load-network
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:). I have to step away for today, but I'll look into it more over the weekend on ow we should be doing this and I'll have a better update on Monday.

**Comment by codingone21** [comment]
* PR for network statuses: https://github.com/onflow/next-docs-v1/pull/155
* Still working on resolving a CORS error with the discourse APIs..
